// Mocks generated by Mockito 5.4.4 from annotations
// in sj_manager/test/competitions/competition_rules_utilities/default_competition_score_creators_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter/material.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:sj_manager/models/simulation_db/competition/competition.dart'
    as _i4;
import 'package:sj_manager/models/simulation_db/competition/rules/utils/competition_score_creator/competition_score_creator.dart'
    as _i11;
import 'package:sj_manager/models/simulation_db/event_series/event_series.dart'
    as _i3;
import 'package:sj_manager/models/simulation_db/standings/score/concrete/jump_score.dart'
    as _i2;
import 'package:sj_manager/models/user_db/country/country.dart' as _i10;
import 'package:sj_manager/models/user_db/hill/hill.dart' as _i5;
import 'package:sj_manager/models/user_db/jumper/jumper.dart' as _i6;
import 'package:sj_manager/models/user_db/team/competition_team.dart' as _i8;
import 'package:sj_manager/models/user_db/team/team.dart' as _i7;
import 'package:sj_manager/utils/multilingual_string.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeJumpScore_0<E> extends _i1.SmartFake implements _i2.JumpScore<E> {
  _FakeJumpScore_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventSeries_1 extends _i1.SmartFake implements _i3.EventSeries {
  _FakeEventSeries_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompetition_2<E> extends _i1.SmartFake
    implements _i4.Competition<E> {
  _FakeCompetition_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHill_3 extends _i1.SmartFake implements _i5.Hill {
  _FakeHill_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJumper_4 extends _i1.SmartFake implements _i6.Jumper {
  _FakeJumper_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompetitionTeam_5<T extends _i7.Team> extends _i1.SmartFake
    implements _i8.CompetitionTeam<T> {
  _FakeCompetitionTeam_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMultilingualString_6 extends _i1.SmartFake
    implements _i9.MultilingualString {
  _FakeMultilingualString_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCountry_7 extends _i1.SmartFake implements _i10.Country {
  _FakeCountry_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IndividualCompetitionScoreCreatingContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockIndividualCompetitionScoreCreatingContext extends _i1.Mock
    implements _i11.IndividualCompetitionScoreCreatingContext {
  MockIndividualCompetitionScoreCreatingContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.JumpScore<_i6.Jumper> get lastJumpScore => (super.noSuchMethod(
        Invocation.getter(#lastJumpScore),
        returnValue: _FakeJumpScore_0<_i6.Jumper>(
          this,
          Invocation.getter(#lastJumpScore),
        ),
      ) as _i2.JumpScore<_i6.Jumper>);

  @override
  _i3.EventSeries get eventSeries => (super.noSuchMethod(
        Invocation.getter(#eventSeries),
        returnValue: _FakeEventSeries_1(
          this,
          Invocation.getter(#eventSeries),
        ),
      ) as _i3.EventSeries);

  @override
  _i4.Competition<_i6.Jumper> get competition => (super.noSuchMethod(
        Invocation.getter(#competition),
        returnValue: _FakeCompetition_2<_i6.Jumper>(
          this,
          Invocation.getter(#competition),
        ),
      ) as _i4.Competition<_i6.Jumper>);

  @override
  int get currentRound => (super.noSuchMethod(
        Invocation.getter(#currentRound),
        returnValue: 0,
      ) as int);

  @override
  _i5.Hill get hill => (super.noSuchMethod(
        Invocation.getter(#hill),
        returnValue: _FakeHill_3(
          this,
          Invocation.getter(#hill),
        ),
      ) as _i5.Hill);

  @override
  _i6.Jumper get entity => (super.noSuchMethod(
        Invocation.getter(#entity),
        returnValue: _FakeJumper_4(
          this,
          Invocation.getter(#entity),
        ),
      ) as _i6.Jumper);
}

/// A class which mocks [TeamCompetitionScoreCreatingContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeamCompetitionScoreCreatingContext extends _i1.Mock
    implements _i11.TeamCompetitionScoreCreatingContext {
  MockTeamCompetitionScoreCreatingContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.JumpScore<_i6.Jumper> get lastJumpScore => (super.noSuchMethod(
        Invocation.getter(#lastJumpScore),
        returnValue: _FakeJumpScore_0<_i6.Jumper>(
          this,
          Invocation.getter(#lastJumpScore),
        ),
      ) as _i2.JumpScore<_i6.Jumper>);

  @override
  _i3.EventSeries get eventSeries => (super.noSuchMethod(
        Invocation.getter(#eventSeries),
        returnValue: _FakeEventSeries_1(
          this,
          Invocation.getter(#eventSeries),
        ),
      ) as _i3.EventSeries);

  @override
  _i4.Competition<_i8.CompetitionTeam<_i7.Team>> get competition =>
      (super.noSuchMethod(
        Invocation.getter(#competition),
        returnValue: _FakeCompetition_2<_i8.CompetitionTeam<_i7.Team>>(
          this,
          Invocation.getter(#competition),
        ),
      ) as _i4.Competition<_i8.CompetitionTeam<_i7.Team>>);

  @override
  int get currentRound => (super.noSuchMethod(
        Invocation.getter(#currentRound),
        returnValue: 0,
      ) as int);

  @override
  _i5.Hill get hill => (super.noSuchMethod(
        Invocation.getter(#hill),
        returnValue: _FakeHill_3(
          this,
          Invocation.getter(#hill),
        ),
      ) as _i5.Hill);

  @override
  _i8.CompetitionTeam<_i7.Team> get entity => (super.noSuchMethod(
        Invocation.getter(#entity),
        returnValue: _FakeCompetitionTeam_5<_i7.Team>(
          this,
          Invocation.getter(#entity),
        ),
      ) as _i8.CompetitionTeam<_i7.Team>);
}

/// A class which mocks [Country].
///
/// See the documentation for Mockito's code generation for more information.
class MockCountry extends _i1.Mock implements _i10.Country {
  MockCountry() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get code => (super.noSuchMethod(
        Invocation.getter(#code),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#code),
        ),
      ) as String);

  @override
  _i9.MultilingualString get multilingualName => (super.noSuchMethod(
        Invocation.getter(#multilingualName),
        returnValue: _FakeMultilingualString_6(
          this,
          Invocation.getter(#multilingualName),
        ),
      ) as _i9.MultilingualString);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);

  @override
  String name(_i13.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #name,
          [context],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #name,
            [context],
          ),
        ),
      ) as String);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i10.Country copyWith({
    String? code,
    _i9.MultilingualString? multilingualName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #code: code,
            #multilingualName: multilingualName,
          },
        ),
        returnValue: _FakeCountry_7(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #code: code,
              #multilingualName: multilingualName,
            },
          ),
        ),
      ) as _i10.Country);
}
