// Mocks generated by Mockito 5.4.4 from annotations
// in sj_manager/test/local_database/ui/database_editor/database_editor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i2;

import 'package:flutter/material.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:rxdart/rxdart.dart' as _i3;
import 'package:sj_manager/models/country.dart' as _i6;
import 'package:sj_manager/repositories/countries/local_storage_multilingual_countries_repository.dart'
    as _i10;
import 'package:sj_manager/repositories/country_flags.dart/country_flags_api.dart'
    as _i11;
import 'package:sj_manager/repositories/database_editing/db_items_local_storage_repository.dart'
    as _i8;
import 'package:sj_manager/repositories/database_editing/db_items_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFile_0 extends _i1.SmartFake implements _i2.File {
  _FakeFile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueStream_1<T1> extends _i1.SmartFake
    implements _i3.ValueStream<T1> {
  _FakeValueStream_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDbItemsRepository_2<T1> extends _i1.SmartFake
    implements _i4.DbItemsRepository<T1> {
  _FakeDbItemsRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_3<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCountry_4 extends _i1.SmartFake implements _i6.Country {
  _FakeCountry_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImageProvider_5<T extends Object> extends _i1.SmartFake
    implements _i7.ImageProvider<T> {
  _FakeImageProvider_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DbItemsLocalStorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDbItemsLocalStorageRepository<T> extends _i1.Mock
    implements _i8.DbItemsLocalStorageRepository<T> {
  MockDbItemsLocalStorageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  T Function(Map<String, dynamic>) get fromJson => (super.noSuchMethod(
        Invocation.getter(#fromJson),
        returnValue: (Map<String, dynamic> json) => _i9.dummyValue<T>(
          this,
          Invocation.getter(#fromJson),
        ),
      ) as T Function(Map<String, dynamic>));

  @override
  set fromJson(T Function(Map<String, dynamic>)? _fromJson) =>
      super.noSuchMethod(
        Invocation.setter(
          #fromJson,
          _fromJson,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> Function(T) get toJson => (super.noSuchMethod(
        Invocation.getter(#toJson),
        returnValue: (T object) => <String, dynamic>{},
      ) as Map<String, dynamic> Function(T));

  @override
  set toJson(Map<String, dynamic> Function(T)? _toJson) => super.noSuchMethod(
        Invocation.setter(
          #toJson,
          _toJson,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.File get storageFile => (super.noSuchMethod(
        Invocation.getter(#storageFile),
        returnValue: _FakeFile_0(
          this,
          Invocation.getter(#storageFile),
        ),
      ) as _i2.File);

  @override
  _i3.ValueStream<Iterable<T>> get items => (super.noSuchMethod(
        Invocation.getter(#items),
        returnValue: _FakeValueStream_1<Iterable<T>>(
          this,
          Invocation.getter(#items),
        ),
      ) as _i3.ValueStream<Iterable<T>>);

  @override
  _i5.Future<_i4.DbItemsRepository<T>> clone() => (super.noSuchMethod(
        Invocation.method(
          #clone,
          [],
        ),
        returnValue: _i5.Future<_i4.DbItemsRepository<T>>.value(
            _FakeDbItemsRepository_2<T>(
          this,
          Invocation.method(
            #clone,
            [],
          ),
        )),
      ) as _i5.Future<_i4.DbItemsRepository<T>>);

  @override
  _i5.Future<void> add(
    T? item, [
    int? index,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [
            item,
            index,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> remove(T? item) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [item],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T> removeAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #removeAt,
          [index],
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #removeAt,
                  [index],
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_3<T>(
              this,
              Invocation.method(
                #removeAt,
                [index],
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadRaw(Iterable<T>? items) => (super.noSuchMethod(
        Invocation.method(
          #loadRaw,
          [items],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> move({
    required int? from,
    required int? to,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #move,
          [],
          {
            #from: from,
            #to: to,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> replace({
    required int? oldIndex,
    required T? newItem,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replace,
          [],
          {
            #oldIndex: oldIndex,
            #newItem: newItem,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadFromSource() => (super.noSuchMethod(
        Invocation.method(
          #loadFromSource,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveToSource() => (super.noSuchMethod(
        Invocation.method(
          #saveToSource,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [LocalStorageMultilingualCountriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageMultilingualCountriesRepository extends _i1.Mock
    implements _i10.LocalStorageMultilingualCountriesRepository {
  MockLocalStorageMultilingualCountriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.File get storageFile => (super.noSuchMethod(
        Invocation.getter(#storageFile),
        returnValue: _FakeFile_0(
          this,
          Invocation.getter(#storageFile),
        ),
      ) as _i2.File);

  @override
  String get languageCode => (super.noSuchMethod(
        Invocation.getter(#languageCode),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#languageCode),
        ),
      ) as String);

  @override
  Iterable<_i6.Country> get countries => (super.noSuchMethod(
        Invocation.getter(#countries),
        returnValue: <_i6.Country>[],
      ) as Iterable<_i6.Country>);

  @override
  _i6.Country get none => (super.noSuchMethod(
        Invocation.getter(#none),
        returnValue: _FakeCountry_4(
          this,
          Invocation.getter(#none),
        ),
      ) as _i6.Country);

  @override
  _i5.Future<void> loadFromSource() => (super.noSuchMethod(
        Invocation.method(
          #loadFromSource,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveToSource() => (super.noSuchMethod(
        Invocation.method(
          #saveToSource,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i6.Country? byCode(String? code) => (super.noSuchMethod(Invocation.method(
        #byCode,
        [code],
      )) as _i6.Country?);
}

/// A class which mocks [CountryFlagsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockCountryFlagsApi extends _i1.Mock implements _i11.CountryFlagsApi {
  MockCountryFlagsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.ImageProvider<Object> imageData(_i6.Country? country) =>
      (super.noSuchMethod(
        Invocation.method(
          #imageData,
          [country],
        ),
        returnValue: _FakeImageProvider_5<Object>(
          this,
          Invocation.method(
            #imageData,
            [country],
          ),
        ),
      ) as _i7.ImageProvider<Object>);
}
