// Mocks generated by Mockito 5.4.4 from annotations
// in sj_manager/test/career_mode_logic/callback_classification_scoring_delegate_by_event_series_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:sj_manager/models/db/event_series/event_series.dart' as _i5;
import 'package:sj_manager/models/db/event_series/event_series_assets.dart'
    as _i4;
import 'package:sj_manager/models/db/event_series/event_series_calendar.dart'
    as _i2;
import 'package:sj_manager/models/db/event_series/event_series_facts.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEventSeriesCalendar_0 extends _i1.SmartFake
    implements _i2.EventSeriesCalendar {
  _FakeEventSeriesCalendar_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventSeriesFacts_1 extends _i1.SmartFake
    implements _i3.EventSeriesFacts {
  _FakeEventSeriesFacts_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventSeriesAssets_2 extends _i1.SmartFake
    implements _i4.EventSeriesAssets {
  _FakeEventSeriesAssets_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_3 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EventSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventSeries extends _i1.Mock implements _i5.EventSeries {
  MockEventSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EventSeriesCalendar get calendar => (super.noSuchMethod(
        Invocation.getter(#calendar),
        returnValue: _FakeEventSeriesCalendar_0(
          this,
          Invocation.getter(#calendar),
        ),
      ) as _i2.EventSeriesCalendar);

  @override
  _i3.EventSeriesFacts get facts => (super.noSuchMethod(
        Invocation.getter(#facts),
        returnValue: _FakeEventSeriesFacts_1(
          this,
          Invocation.getter(#facts),
        ),
      ) as _i3.EventSeriesFacts);

  @override
  _i4.EventSeriesAssets get assets => (super.noSuchMethod(
        Invocation.getter(#assets),
        returnValue: _FakeEventSeriesAssets_2(
          this,
          Invocation.getter(#assets),
        ),
      ) as _i4.EventSeriesAssets);

  @override
  DateTime get startDate => (super.noSuchMethod(
        Invocation.getter(#startDate),
        returnValue: _FakeDateTime_3(
          this,
          Invocation.getter(#startDate),
        ),
      ) as DateTime);
}
